"use client";
import { FormEvent, useEffect, useState } from "react";
type Result = { data: { playerId: string; nickname: string; level?: number; rank?: string }; cache: { isStale: boolean; refreshBlockedReason?: string } };
export default function PlayersPage() {
  const [nickname, setNickname] = useState(""); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(""); const [recent, setRecent] = useState<string[]>([]);
  useEffect(() => setRecent(JSON.parse(localStorage.getItem("marvel:recent-players") ?? "[]")), []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setResult(null); const response = await fetch(`/api/players/search?nickname=${encodeURIComponent(nickname)}`); if (!response.ok) { setError(response.status === 429 ? "오늘 API 호출량이 많아 새 플레이어 정보를 갱신할 수 없습니다." : "플레이어를 찾지 못했습니다. 닉네임을 확인해 주세요."); return; } const body = await response.json() as Result; setResult(body); const next = [body.data.nickname, ...recent.filter(x => x !== body.data.nickname)].slice(0, 6); setRecent(next); localStorage.setItem("marvel:recent-players", JSON.stringify(next)); }
  return <section><p className="eyebrow">PLAYER SEARCH</p><h1>플레이어 검색</h1><form onSubmit={submit} className="search"><input value={nickname} onChange={e => setNickname(e.target.value)} placeholder="닉네임 또는 playerId" aria-label="닉네임 또는 playerId"/><button>검색</button></form>{recent.length > 0 && <div className="recent"><span>최근 검색</span>{recent.map(name => <button key={name} onClick={() => setNickname(name)}>{name}</button>)}</div>}{error && <p className="notice error">{error}</p>}{result && <a className="player-card" href={`/players/${encodeURIComponent(result.data.playerId)}`}><div><strong>{result.data.nickname}</strong><p>{result.data.rank ?? "랭크 정보 없음"} · 레벨 {result.data.level ?? "-"}</p></div><span className={result.cache.isStale ? "badge stale" : "badge"}>{result.cache.isStale ? "최근 저장된 데이터 기준" : "최신 데이터 기준"}</span></a>}</section>;
}
